default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'password') %>
  host: <%= ENV.fetch('POSTGRES_HOST', 'postgres') %>

development:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB', 'lms_development') %>

test:
  <<: *default
  database: lms_test

production:
  <<: *default
  database: lms_production 