default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password
  host: postgres

development:
  <<: *default
  database: lms_development

test:
  <<: *default
  database: lms_test

production:
  <<: *default
  database: lms_production 